package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"log"

	"github.com/awoelf/go-retail/graph/model"
)

// AddItem is the resolver for the addItem field.
func (r *mutationResolver) AddItem(ctx context.Context, input *model.NewItem) (*model.Item, error) {
	res, err := r.Services.Item.AddItem(ctx, input)
	if err != nil {
		log.Fatal(err)
	}

	return &model.Item{
		DepartmentID:   res.DepartmentID,
		Name:           res.Name,
		Price:          res.Price,
		Qty:            res.Qty,
		QtySold:        res.QtySold,
		Category:       res.Category,
		Promo:          res.Promo,
		PromoPrice:     res.PromoPrice,
		TotalSalesItem: res.TotalSalesItem,
		Aisle:          res.Aisle,
	}, nil
}

// UpdateItem is the resolver for the updateItem field.
func (r *mutationResolver) UpdateItem(ctx context.Context, input *model.UpdateItem) (*model.Item, error) {
	res, err := r.Services.Item.UpdateItem(ctx, input)
	if err != nil {
		log.Fatal(err)
	}

	return &model.Item{
		ID:             res.ID,
		DepartmentID:   *res.DepartmentID,
		Name:           *res.Name,
		Price:          *res.Price,
		Qty:            *res.Qty,
		QtySold:        res.QtySold,
		Category:       res.Category,
		Promo:          res.Promo,
		PromoPrice:     res.PromoPrice,
		TotalSalesItem: res.TotalSalesItem,
		Aisle:          *res.Aisle,
	}, nil
}

// DeleteItem is the resolver for the deleteItem field.
func (r *mutationResolver) DeleteItem(ctx context.Context, id *string) (*string, error) {
	err := r.Services.Item.DeleteItem(ctx, id)
	if err != nil {
		log.Fatal(err)
	}

	return id, nil
}

// SellTransaction is the resolver for the sellTransaction field.
func (r *mutationResolver) SellTransaction(ctx context.Context, input *model.NewTransaction) (*model.Transaction, error) {
	res, err := r.Services.Transaction.SellTransaction(ctx, input)

	if err != nil {
		log.Fatal(err)
	}

	return res, nil
}

// ReturnTransaction is the resolver for the returnTransaction field.
func (r *mutationResolver) ReturnTransaction(ctx context.Context, input *model.NewTransaction) (*model.Transaction, error) {
	res, err := r.Services.Transaction.ReturnTransaction(ctx, input)

	if err != nil {
		log.Fatal(err)
	}

	return res, nil
}

// OrderItems is the resolver for the orderItems field.
func (r *mutationResolver) OrderItems(ctx context.Context, input *model.ItemOrder) (*model.Item, error) {
	res, err := r.Services.Item.OrderItems(ctx, input)
	if err != nil {
		log.Fatal(err)
	}

	return &model.Item{
		ID: res.ID,
	}, nil
}

// StartSaleItem is the resolver for the startSaleItem field.
func (r *mutationResolver) StartSaleItem(ctx context.Context, input *model.ItemPromotion) (*model.Item, error) {
	res, err := r.Services.Item.StartSaleItem(ctx, input)
	if err != nil {
		log.Fatal(err)
	}

	return &model.Item{
		ID:         res.ID,
		Promo:      &res.Promo,
		PromoPrice: &res.PromoPrice,
	}, nil
}

// EndSaleItem is the resolver for the endSaleItem field.
func (r *mutationResolver) EndSaleItem(ctx context.Context, input *string) (*string, error) {
	_, err := r.Services.Item.EndSaleItem(ctx, input)
	if err != nil {
		log.Fatal(err)
	}

	return input, nil
}

// AddDepartment is the resolver for the addDepartment field.
func (r *mutationResolver) AddDepartment(ctx context.Context, input *model.NewDepartment) (*model.Department, error) {
	res, err := r.Services.Department.AddDepartment(ctx, input)
	if err != nil {
		log.Fatal(err)
	}

	return &model.Department{
		Name: res.Name,
	}, nil
}

// UpdateDepartment is the resolver for the updateDepartment field.
func (r *mutationResolver) UpdateDepartment(ctx context.Context, input *model.UpdateDepartment) (*model.Department, error) {
	res, err := r.Services.Department.UpdateDepartment(ctx, input)
	if err != nil {
		log.Fatal(err)
	}

	return &model.Department{
		Name: res.Name,
	}, nil
}

// DeleteDepartment is the resolver for the deleteDepartment field.
func (r *mutationResolver) DeleteDepartment(ctx context.Context, id *string) (*string, error) {
	err := r.Services.Department.DeleteDepartment(ctx, id)
	if err != nil {
		log.Fatal(err)
	}

	return id, nil
}

// AddManager is the resolver for the addManager field.
func (r *mutationResolver) AddManager(ctx context.Context, input *model.NewManager) (*model.Manager, error) {
	res, err := r.Services.Manager.AddManager(ctx, input)
	if err != nil {
		log.Fatal(err)
	}

	return &model.Manager{
		FirstName:    res.FirstName,
		LastName:     res.LastName,
		DepartmentID: &res.DepartmentID,
	}, nil
}

// UpdateManager is the resolver for the updateManager field.
func (r *mutationResolver) UpdateManager(ctx context.Context, input *model.UpdateManager) (*model.Manager, error) {
	res, err := r.Services.Manager.UpdateManager(ctx, input)
	if err != nil {
		log.Fatal(err)
	}

	return &model.Manager{
		ID:           res.ID,
		FirstName:    res.FirstName,
		LastName:     res.LastName,
		DepartmentID: &res.DepartmentID,
	}, nil
}

// DeleteManager is the resolver for the deleteManager field.
func (r *mutationResolver) DeleteManager(ctx context.Context, id *string) (*string, error) {
	err := r.Services.Manager.DeleteManager(ctx, id)
	if err != nil {
		log.Fatal(err)
	}

	return id, nil
}

// GetAllItems is the resolver for the getAllItems field.
func (r *queryResolver) GetAllItems(ctx context.Context) ([]*model.Item, error) {
	res, err := r.Services.Item.GetAllItems(ctx)
	if err != nil {
		log.Fatal(err)
	}

	return res, nil
}

// GetItemByID is the resolver for the getItemById field.
func (r *queryResolver) GetItemByID(ctx context.Context, id *string) (*model.Item, error) {
	res, err := r.Services.Item.GetItemById(ctx, id)
	if err != nil {
		log.Fatal(err)
	}

	return res, nil
}

// GetTopItems is the resolver for the getTopItems field.
func (r *queryResolver) GetTopItems(ctx context.Context) ([]*model.Item, error) {
	res, err := r.Services.Item.GetTopItems(ctx)
	if err != nil {
		log.Fatal(err)
	}

	return res, nil
}

// GetItemsByCategory is the resolver for the getItemsByCategory field.
func (r *queryResolver) GetItemsByCategory(ctx context.Context, category *string) ([]*model.Item, error) {
	res, err := r.Services.Item.GetItemsByCategory(ctx, category)
	if err != nil {
		log.Fatal(err)
	}

	return res, nil
}

// GetAllDepartments is the resolver for the getAllDepartments field.
func (r *queryResolver) GetAllDepartments(ctx context.Context) ([]*model.Department, error) {
	res, err := r.Services.Department.GetAllDepartments(ctx)

	if err != nil {
		log.Fatal(err)
	}

	return res, nil
}

// GetDepartmentByID is the resolver for the getDepartmentById field.
func (r *queryResolver) GetDepartmentByID(ctx context.Context, id *string) (*model.Department, error) {
	res, err := r.Services.Department.GetDepartmentById(ctx, id)

	if err != nil {
		log.Fatal(err)
	}

	return res, nil
}

// GetTopDepartments is the resolver for the getTopDepartments field.
func (r *queryResolver) GetTopDepartments(ctx context.Context) ([]*model.Department, error) {
	res, err := r.Services.Department.GetTopDepartments(ctx)

	if err != nil {
		log.Fatal(err)
	}

	return res, nil
}

// GetAllManagers is the resolver for the getAllManagers field.
func (r *queryResolver) GetAllManagers(ctx context.Context) ([]*model.Manager, error) {
	res, err := r.Services.Manager.GetAllManagers(ctx)
	if err != nil {
		log.Fatal(err)
	}

	return res, nil
}

// GetManagerByID is the resolver for the getManagerById field.
func (r *queryResolver) GetManagerByID(ctx context.Context, id *string) (*model.Manager, error) {
	res, err := r.Services.Manager.GetManagerById(ctx, id)
	if err != nil {
		log.Fatal(err)
	}

	return res, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
