// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Aisle struct {
	ID           int    `json:"id"`
	DepartmentID string `json:"departmentId"`
}

type Department struct {
	ID                 int      `json:"id"`
	Name               string   `json:"name"`
	TotalSalesWeekDept *float64 `json:"totalSalesWeekDept,omitempty"`
}

type Item struct {
	ID                 int      `json:"id"`
	Name               string   `json:"name"`
	Price              float64  `json:"price"`
	Qty                int      `json:"qty"`
	Category           string   `json:"category"`
	Promotion          *bool    `json:"promotion,omitempty"`
	PromotionPrice     *float64 `json:"promotionPrice,omitempty"`
	Replenish          *bool    `json:"replenish,omitempty"`
	TotalSalesWeekItem *float64 `json:"totalSalesWeekItem,omitempty"`
	AisleID            string   `json:"aisleId"`
	DepartmentID       string   `json:"departmentId"`
}

type Manager struct {
	ID           int     `json:"id"`
	FirstName    string  `json:"firstName"`
	LastName     string  `json:"lastName"`
	DepartmentID *string `json:"departmentId,omitempty"`
}

type NewAisle struct {
	DepartmentID string `json:"departmentId"`
}

type NewDepartment struct {
	Name string `json:"name"`
}

type NewItem struct {
	Name         string  `json:"name"`
	Price        float64 `json:"price"`
	Qty          int     `json:"qty"`
	Category     string  `json:"category"`
	AisleID      string  `json:"aisleId"`
	DepartmentID string  `json:"departmentId"`
}

type NewManager struct {
	FirstName    string  `json:"firstName"`
	LastName     string  `json:"lastName"`
	DepartmentID *string `json:"departmentId,omitempty"`
}
