DROP DATABASE IF EXISTS go_retail_db;

CREATE DATABASE go_retail_db;

USE go_retail_db;

CREATE TABLE IF NOT EXISTS Departments(
    ID INT NOT NULL AUTO_INCREMENT UNIQUE,
    Name VARCHAR(127) NOT NULL UNIQUE,
    TotalSalesDept FLOAT DEFAULT(0) NOT NULL,
	CreatedAt TIMESTAMP DEFAULT(NOW()),
	UpdatedAt TIMESTAMP DEFAULT(NOW()),
    
	INDEX(ID),
    
    PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS Managers(
    ID INT NOT NULL AUTO_INCREMENT UNIQUE,
    FirstName VARCHAR(127) NOT NULL,
    LastName VARCHAR(127) NOT NULL,
    DepartmentID INT,
	CreatedAt TIMESTAMP DEFAULT(NOW()),
	UpdatedAt TIMESTAMP DEFAULT(NOW()),

    
    INDEX(ID),
    INDEX(DepartmentID),
    
    FOREIGN KEY(DepartmentID)
    REFERENCES Departments(ID)
    ON UPDATE CASCADE,
    
    PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS Items(
    ID INT NOT NULL AUTO_INCREMENT UNIQUE,
    Name VARCHAR(127) NOT NULL UNIQUE,
    Price FLOAT NOT NULL,
    Qty INT NOT NULL,
	Category VARCHAR(127) NOT NULL DEFAULT("NONE"),
    Promotion BOOLEAN DEFAULT(FALSE) NOT NULL,
    Replenish BOOLEAN DEFAULT(FALSE) NOT NULL,
    TotalSalesItem FLOAT DEFAULT(0) NOT NULL,
	Aisle INT NOT NULL,
	DepartmentID INT NOT NULL,
	CreatedAt TIMESTAMP DEFAULT(NOW()),
	UpdatedAt TIMESTAMP DEFAULT(NOW()),

    INDEX(ID),
    INDEX(DepartmentID),
    
    FOREIGN KEY(DepartmentID)
    REFERENCES Departments(ID)
    ON UPDATE CASCADE,
    
    PRIMARY KEY(ID)
);